language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
    - '$HOME/.sonar/cache'
addons:
  sonarcloud:
    organization: "aborozdykh"
    token:
      secure: "$SONAR_TOKEN"
script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=internet-shop -Dsonar.organization=aborozdykh -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
env:
  SONAR_TOKEN: ${{ secrets.INTERNET_SHOP_SONAR_TOKEN }}